# Generated by Django 4.2.29 on 2026-03-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InferenceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(max_length=64, unique=True)),
                ("original_image", models.ImageField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "enhanced_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="outputs/%Y/%m/%d/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="distill_v4", max_length=32),
                ),
                ("parameters", models.JSONField(blank=True, null=True)),
                ("meta_info", models.JSONField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=16)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="users.miniprogramuser",
                    ),
                ),
            ],
            options={
                "db_table": "inference_record",
                "ordering": ["-created_at"],
            },
        ),
    ]
