# Generated by Django 4.2.29 on 2026-03-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerecord",
            name="aesthetic_after",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencerecord",
            name="aesthetic_before",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencerecord",
            name="aesthetic_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("unavailable", "Unavailable"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
