# Generated by Django 4.2.29 on 2026-03-29 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0002_inferencerecord_aesthetic_after_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=128)),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "inference_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo",
                        to="inference.inferencerecord",
                    ),
                ),
            ],
            options={
                "db_table": "photo_record",
                "ordering": ["-saved_at"],
            },
        ),
    ]
