# Generated by Django 4.2.29 on 2026-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0003_photo_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="photorecord",
            name="enhanced_image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="photorecord",
            name="original_image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
