# Generated by Django 4.2.29 on 2026-03-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0004_photo_record_image_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="inferencerecord",
            name="enhanced_image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inferencerecord",
            name="original_image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="PhotoRecord",
        ),
    ]
